apiVersion: skaffold/v4beta11
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketz-dev-433920
  artifacts:
    - image: eu.gcr.io/ticketz-dev-433920/auth
    #- image: moswilamdev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .